### PR TITLE
Fixed native Demo ndk-build path, $ORX path added for locating orx lib.

### PR DESCRIPTION
**Pull request by sausagejohnson**

### CODE REVIEW

**Comment by iarwain** [comment]
I'll hold for now on this one as I might have reverted something incorrectly (the /cpp -> /jni path) in a recent commit. Could you try to move the files that are under /jni back to /cpp and see if it works?

**Comment by sausagejohnson** [comment]
Can do. I noticed in your "attempt to fix" PR you did that, and assumed it was a mistake. I'll check it out and see.

**Comment by sausagejohnson** [comment]
Yep I'll revert this and restore the folder change. And I won't change the gradle version as this works with Android Studio 2.3.3. Gradle updates can be handled easily enough by the user with a mouse click.

**Comment by iarwain** [comment]
Yes, sorry, I'm not sure how I ended up doing that, I only meant to fix the paths inside the makefiles that were pointing to Loki's directories.

**Comment by sausagejohnson** [comment]
All good. PR is ready. _cpp_ appears to not be acceptable. Changing _jni_ to _cpp_ errors. Therefore must be a convention.

**Pull request merged**
