### PR TITLE
-Wextra Linux clang build warnings

### PR DESCRIPTION
**Pull request by OneArb**
Summary of Linux clang build warnings when compiling with -Wextra

### CODE REVIEW

**Comment by OneArb** [comment]
The goal would be to come up with a clang compiler orx supported option set allowing -Wextra compilation.

**Comment by iarwain** [comment]
Thank you for running clang with all the warnings.

Here's a preliminary list of warnings that I think are not really relevant to our use case:

- [-Wc11-extensions]
- [-Wdouble-promotion]
- [-Wfloat-equal]
- [-Wformat-nonliteral]
- [-Wgnu-zero-variadic-macro-arguments]
- [-Wpadded]
- [-Wpedantic]
- [-Wreserved-id-macro]
- [-Wstrict-prototypes]
- [-Wswitch-enum]

If you have a list of the defects found with the other flags, I'd be happy to have a look.

**Comment by iarwain** [comment]
Also I think this discussion would be nice to have at https://forum.orx-project.org as it'll remain with orx while the github repository might not be as permanent.

**Comment by OneArb** [comment]
To keep the ball rolling, I'll post the warning list here and will follow-up with a forum post later.

Here is a new batch of warnings to review, including a summary of the warnings already reviewed.

[warning-type-list-status.txt](https://github.com/orx/orx/files/3752758/warning-type-list-status.txt)
[llvm warnings - summary - part 2.txt](https://github.com/orx/orx/files/3752759/llvm.warnings.-.summary.-.part.2.txt)

**Comment by iarwain** [comment]
Sorry for the delay, I'll be back on it this next weekend.

**Comment by OneArb** [comment]
Thanks for the follow up.

I'll pursue the thread on the forum.

**Comment by OneArb** [comment]
A list of the keepers

- tabulated by warning type
- extern headers removed
- keeper flags
- -std=c99
- -Weverything

[llvm warnings - extern remove - orx.txt](https://github.com/orx/orx/files/3934208/llvm.warnings.-.extern.remove.-.orx.txt)

**Pull request closed without merging**
