### PR TITLE
portable acquiring of file descriptor

### PR DESCRIPTION
**Pull request by Ondra09**
Fix for mingw make on windows.

### CODE REVIEW

**Comment by iarwain** [comment]
Thanks for the PR.
The original issue was an incorrect combination of #ifdefs (assuming all windows were MSVC).

Tonight I'll push a slightly different fix, inspired from yours that should uniformize of GetSize() vs GetTime().

**Comment by iarwain** [comment]
Fix submitted (9303e5ca13685c2bf395f7fd572b1fa613068559)

**Comment by iarwain** [comment]
Fix submitted (9303e5ca13685c2bf395f7fd572b1fa613068559)

**Comment by Ondra09** [comment]
Great, thank you budy.

**Pull request closed without merging**
