### PR TITLE
Updating to latest android NDK.

### PR DESCRIPTION
**Pull request by danvd**
Hi @iarwain ,
Hopefully now changed code can be compiled and linked successfully :crossed_fingers: 
However one issue still persists. All binary android dependencies were compiled with gnustl_static and now the latter is mixed with libc++_shared at runtime. 
So the next step is to do the same work for all extdeps. I'm ready to finish this task if you can point me where to send PRs. To make it more robust prelinked libs can be avoided (for android). 

Thank  you.

### CODE REVIEW

**Comment by romainkillian** [comment]
Hi @danvd,

Thanks for the new PR. Indeed, dependencies need to get the same treatment.
I already added a Trello card for building x86_64 binaries a couple of days ago and will modify it to mention the required gnustl_static -> libc++_shared + API update changes.

I can take care of it in the coming days, it might take a short while as I wasn't the one who originally compiled those and I'm sure I'll hit some snags given that I'm not familiar with Android tooling.

If you're willing to have a look at it, I'd sure appreciate it however it might be less convenient for you as it's not hosted with git/github.com but with hg/bitbucket.org at https://bitbucket.org/orx/orx-extern

**Comment by danvd** [comment]
Hi @romainkillian,
Thank you. 
I just created a PR on bitbucket consisting of mentioned changes to orx-extern:
https://bitbucket.org/orx/orx-extern/pull-requests/2

**Comment by iarwain** [comment]
Perfect, thanks, I'll check all that tonight.

**Comment by danvd** [comment]
Updated android and android-native (libs + demos) to support x86_64 as well as orx-extern on bitbucket.

**Comment by iarwain** [comment]
Thanks a lot. I'll check all that tonight.

**Comment by danvd** [comment]
Great, thank you!

**Comment by iarwain** [comment]
Well, you did all the work @danvd, thank you! Don't hesitate to come and chat with us on https://gitter.im/orx/orx by the way.

**Pull request merged**
