### PR TITLE
Minor android improvements

### PR DESCRIPTION
**Pull request by znakeeye**
* Fixed a bug in `orxMouse_GetMoveDelta` on both iOS (untested) and Android (verified).
* Got rid of obsolete NEON runtime checks (`cpufeatures` library).
* Android projects upgraded in `Android Studio Hedgehog` (released one hour ago, hehe).
* AGDK libraries bumped. Nothing special here.
* Updated to `NDK r26b`. See below.

**`NDK r26b`** is an important milestone for native Android development. See [changelog](https://github.com/android/ndk/wiki/Changelog-r26). The most important piece; `SDK v21` now is the minimum supported version. Hence `orxAndroid` now requires `SDK v21` or later.

When comparing binaries, I realized that the `APK` size actually _increased_ after upgrade. I registered [issue #1953](https://github.com/android/ndk/issues/1953) where Google devs concluded that this is mostly expected (arm32 is not built as thumb). We can expect a fix in `r26c`.

All in all, we are opting in to the latest and greatest library versions. Let's test the integration thoroughly.

### CODE REVIEW

**Comment by iarwain** [comment]
Thanks for the PR! I'll have a look at it this weekend.

**Comment by loki666** [comment]
probably the build scripts for orxExtern libs should also be update to new SDK/minAPI

**Comment by znakeeye** [comment]
> probably the build scripts for orxExtern libs should also be update to new SDK/minAPI
> 
> @znakeeye regarding your comment about the size, it's weird, because I think I remember disabling arm thumb for ARM see:
> 
> https://github.com/orx/orx/blob/9be9b446a8331c42a1bb5fdc8da77820e5565971/code/build/android/orx/src/main/jni/Android.mk#L87
> 
> but maybe it's about the debug symbol stripping, see
> 
> https://github.com/orx/orx/blob/9be9b446a8331c42a1bb5fdc8da77820e5565971/code/build/android/orx/src/main/jni/Application.mk#L5

Since we are using an `.AAR`, we shouldn't (afaik) strip the symbols. The symbols will be stripped when the libs are consumed in the app itself. I think that's why I changed that some time back. I might have a note about that somewhere...

Not sure about `LOCAL_ARM_MODE` though. Maybe it's there for performance reasons?

As for the SDK/minAPI in extern, we could change them as well. But the build script will in fact rebuild all libraries, so I expect the root level minSdk (build.gradle) to propagate to all those libraries. Not verified though.

**Comment by iarwain** [comment]
Woops, wrong button...

**Pull request merged**
